// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchMangaByTitle(arg1) {
  return window['go']['main']['App']['FetchMangaByTitle'](arg1);
}

export function FetchMangaDetails(arg1) {
  return window['go']['main']['App']['FetchMangaDetails'](arg1);
}

export function FormatCoverArtUrl(arg1, arg2) {
  return window['go']['main']['App']['FormatCoverArtUrl'](arg1, arg2);
}

export function UnmarshalMangaRelationships(arg1) {
  return window['go']['main']['App']['UnmarshalMangaRelationships'](arg1);
}
