// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchChapterImages(arg1) {
  return window['go']['main']['App']['FetchChapterImages'](arg1);
}

export function FetchMangaByTitle(arg1) {
  return window['go']['main']['App']['FetchMangaByTitle'](arg1);
}

export function FetchMangaChapters(arg1) {
  return window['go']['main']['App']['FetchMangaChapters'](arg1);
}

export function FetchMangaDetails(arg1) {
  return window['go']['main']['App']['FetchMangaDetails'](arg1);
}

export function FormatChapterImageUrls(arg1) {
  return window['go']['main']['App']['FormatChapterImageUrls'](arg1);
}

export function FormatCoverArtUrl(arg1, arg2) {
  return window['go']['main']['App']['FormatCoverArtUrl'](arg1, arg2);
}

export function HttpRequest(arg1) {
  return window['go']['main']['App']['HttpRequest'](arg1);
}

export function PrintHelper(arg1) {
  return window['go']['main']['App']['PrintHelper'](arg1);
}

export function UnmarshalMangaRelationships(arg1) {
  return window['go']['main']['App']['UnmarshalMangaRelationships'](arg1);
}
