// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchChapterImages(arg1:string):Promise<Array<string>>;

export function FetchMangaByTitle(arg1:string):Promise<main.SearchedMangas>;

export function FetchMangaChapters(arg1:string):Promise<main.MangaChapters>;

export function FetchMangaDetails(arg1:string):Promise<main.Manga>;

export function FormatChapterImageUrls(arg1:main.ChapterImagesMetadata):Promise<Array<string>>;

export function FormatCoverArtUrl(arg1:string,arg2:string):Promise<string>;

export function HttpRequest(arg1:string):Promise<Array<number>>;

export function PrintHelper(arg1:any):Promise<void>;

export function UnmarshalMangaRelationships(arg1:Array<main.MangaRelationships>):Promise<Array<main.AuthorAttributes>|main.CoverArtAttributes>;
