// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchMangaByTitle(arg1:string):Promise<main.SearchedMangas>;

export function FetchMangaDetails(arg1:string):Promise<main.Manga>;

export function FormatCoverArtUrl(arg1:string,arg2:string):Promise<string>;

export function UnmarshalMangaRelationships(arg1:Array<main.MangaRelationships>):Promise<main.AuthorAttributes|main.CoverArtAttributes>;
